In [1]:
# gradient flow


In [13]:
#
import numpy as np 
import torch 
n=5
m=6 
l=7

A=torch.rand(n,m,requires_grad=True)
B=torch.rand(m,l)
C=torch.rand(n,l)

loss=torch.sum(A.matmul(B)*C)
loss.backward()


print("Gradient with respect to A:", A.grad)
print('C B is:', C.matmul(B.T))

Gradient with respect to A: tensor([[2.0364, 1.1966, 1.4805, 1.4238, 1.2298, 2.2388],
        [1.6087, 1.2380, 1.4918, 1.4684, 1.3202, 2.0814],
        [1.2761, 0.8264, 1.2207, 1.0838, 1.1076, 2.0173],
        [1.7019, 0.9980, 1.3544, 1.1629, 1.4505, 2.2074],
        [1.9209, 0.9202, 2.0139, 1.5514, 1.2220, 2.6079]])
C B is: tensor([[2.0364, 1.1966, 1.4805, 1.4238, 1.2298, 2.2388],
        [1.6087, 1.2380, 1.4918, 1.4684, 1.3202, 2.0814],
        [1.2761, 0.8264, 1.2207, 1.0838, 1.1076, 2.0173],
        [1.7019, 0.9980, 1.3544, 1.1629, 1.4505, 2.2074],
        [1.9209, 0.9202, 2.0139, 1.5514, 1.2220, 2.6079]])


In [29]:
p=np.array([0.3,0.4,0.5])
gamma=np.diag(p)
C1=np.random.rand(3,3)

result1=gamma.dot(C1).dot(gamma.T)
result2=(gamma.dot(np.ones((3,1))).dot(p.reshape((1,3))))
result3=p.reshape((3,1)).dot(p.reshape((1,3)))
print(result1)
print(result2)
print(result3)

[[0.02265448 0.04108533 0.03445348]
 [0.0003229  0.06095261 0.12752515]
 [0.09098789 0.16764977 0.11646774]]
[[0.09 0.12 0.15]
 [0.12 0.16 0.2 ]
 [0.15 0.2  0.25]]
[[0.09 0.12 0.15]
 [0.12 0.16 0.2 ]
 [0.15 0.2  0.25]]


In [26]:
gamma

array([0.3])