In [1]:
# gradient flow


In [2]:
#
import numpy as np 
import torch 
n=5
m=6 
l=7

A=torch.rand(n,m,requires_grad=True)
B=torch.rand(m,l)
C=torch.rand(n,l)

loss=torch.sum(A.matmul(B)*C)
loss.backward()


print("Gradient with respect to A:", A.grad)
print('C B is:', C.matmul(B.T))

Gradient with respect to A: tensor([[2.4738, 1.5374, 1.6018, 2.5614, 2.1059, 1.8032],
        [1.4361, 1.9887, 1.7387, 2.0531, 0.9833, 1.6734],
        [2.5670, 1.4793, 1.7064, 2.7541, 2.4785, 2.3514],
        [2.9891, 1.4502, 1.5034, 2.3759, 2.1021, 2.0543],
        [2.6082, 1.9362, 1.6010, 2.0288, 1.7324, 2.2117]])
C B is: tensor([[2.4738, 1.5374, 1.6018, 2.5614, 2.1059, 1.8032],
        [1.4361, 1.9887, 1.7387, 2.0531, 0.9833, 1.6734],
        [2.5670, 1.4793, 1.7064, 2.7541, 2.4785, 2.3514],
        [2.9891, 1.4502, 1.5034, 2.3759, 2.1021, 2.0543],
        [2.6082, 1.9362, 1.6010, 2.0288, 1.7324, 2.2117]])


In [29]:
p=np.array([0.3,0.4,0.5])
gamma=np.diag(p)
C1=np.random.rand(3,3)

result1=gamma.dot(C1).dot(gamma.T)
result2=(gamma.dot(np.ones((3,1))).dot(p.reshape((1,3))))
result3=p.reshape((3,1)).dot(p.reshape((1,3)))
print(result1)
print(result2)
print(result3)

[[0.02265448 0.04108533 0.03445348]
 [0.0003229  0.06095261 0.12752515]
 [0.09098789 0.16764977 0.11646774]]
[[0.09 0.12 0.15]
 [0.12 0.16 0.2 ]
 [0.15 0.2  0.25]]
[[0.09 0.12 0.15]
 [0.12 0.16 0.2 ]
 [0.15 0.2  0.25]]


In [26]:
gamma

array([0.3])